# These are supported funding model platforms

github: [YOUR_GITHUB_USERNAME]
patreon: YOUR_PATREON_USERNAME
open_collective: YOUR_OPEN_COLLECTIVE_NAME
ko_fi: YOUR_KO_FI_USERNAME
tidelift: YOUR_TIDELIFT_PLATFORM
custom: ['https://your-custom-donation-link.com']
